### ISSUE TITLE
Need Help with creating a few filters for easy list.

### ISSUE THREAD

**Issue by MrWaste** [My-External-Stuff/ublockorigin-rules#11]
Could you help me out? I am trying to create a filter list to block brave's new search engine tracking js. 

`https://cdn.search.brave.com/serp/v1/static/serp-js/b3ebc5685fead384a052e73235e19ec4cf3cb484541fa6eb67defdf57127e2bd-telemetry.bundle.js`

Examples:
! -----------------------General advert blocking filters-----------------------!
! *** easylist:easylist/easylist_general_block.txt ***
&advert_
&adzone=
-ad/dist/
-ad/embed.
-ad/iframe/

I only do Ad blocking Dns, I am new to filters. In the past you have added my list to community lists and help me out with other things. I am really grateful for all your help in the past! I haven't seen anyone blocking this script yet so that's why I am here today. If this works I will submitting this to the easy list github page then they can add this. Please let me know if you could help me out, THANK YOU!

Ps, there is no way to block it without a filter because they are using everything within the same domain. `cdn.search.brave.com`

My github lists:
`https://github.com/MrWaste/Ad-BlockList-2019-08-31`

Brave usage-metrics:
`https://search.brave.com/help/usage-metrics`

**Comment by spirillen** [comment]
For the brave site you can do: 

```
! 2021-08-09 https://search.brave.com
||cdn.search.brave.com/serp/v1/static/serp-js/*-telemetry.bundle.js$script
||brave.com/*/usage-metrics
```

However here is a broader one, notice the risk of FP's

```
||brave.com/*/*-telemetry.bundle.js$script
||brave.com/*/usage-metrics
```

![image](https://user-images.githubusercontent.com/44526987/128754266-144dafb2-e270-468c-a874-38940741d984.png)


IS this what you asked for??
