### ISSUE TITLE
general anti-whitelist rules

### ISSUE THREAD

**Issue by mtxadmin** [My-External-Stuff/ublockorigin-rules#3]
Hello.

If you really want to do general anti-whitelist rules, you can write them with $important flag. For example,

googletagmanager.com$important
google-analytics.com$important

Instead of your many rules:
@@||googletagmanager.com/gtm.js$domain=imgur.com,badfilter
@@||googletagmanager.com/gtag/js$domain=malwaretips.com$badfilter
@@||googletagmanager.com/gtm.js$domain=programme-tv.net$badfilter
@@||google-analytics.com/plugins/ua/linkid.js$domain=line.me$badfilter
@@||googletagmanager.com/gtm.js$domain=superesportes.com.br$badfilter
@@||googletagmanager.com/gtm.js$domain=jbc.be$badfilter
@@||googletagmanager.com/gtm.js$domain=fooda.com$badfilter
@@||google-analytics.com/cx/api.js$domain=pcloud.com$badfilter
...

I strongly dislike such whitelists too :-)

**Comment by spirillen** [comment]
Hi @mtxadmin I was doing that to begin with, but here is why I changed that practice

<https://github.com/spirillen/dns-rpz-integration/issues/17> There are some very good comments and hints to why use `badfilter` rather than important.

In short, it turns out that a `@@||` rule actually can overrule a `important`rule especially from your own example above, so the safest way it to actually implant both solutions. :thinking:

**Comment by mtxadmin** [comment]
In my experience, $important rule has the absolute priority and cannot be whitelisted by `@@||` . If there is any contrary example, I would like to see it. In my experience, I never saw such behavior, but maybe I am wrong.

In the other hand, if you want use $badfilter for disable whitelisting, you have to list ALL rules with such domain in ALL variants from ALL possible filterlists. 

I mean, if some filterlist has rule
`@@||googletagmanager.com/gtm.js$domain=domain1`
you have to disable it with
`@@||googletagmanager.com/gtm.js$domain=domain1,badfilter`
And if that rule would changed to
`@@||googletagmanager.com/gtm.js$domain=domain1|domain2`
your rule will stop disabling it (yes?) and you have to update it too. As you can imagine, this is practically unreal.

In my filterlist, I usually marked all well-known ad networks etc with $important flag.

**Comment by mtxadmin** [comment]
Update: I checked https://github.com/spirillen/ublockorigin-rules/issues/5 and do not see any contradictions. And about half of the example is described in the uBO documentation (https://github.com/gorhill/ublock/wiki/Static-filter-syntax etc)

**Comment by mtxadmin** [comment]
Also ping @Yuki2718 with his https://github.com/Yuki2718/adblock/blob/master/medium_mode/anti-allowlist.txt :-)

**Comment by spirillen** [comment]
> In my filterlist, I usually marked all well-known ad networks etc with $important flag just to prevent whitelisting.

Those are in my rpz project :smiling_imp: <https://www.mypdns.org/project/view/12/>

**Comment by THEtomaso** [comment]
> In my experience, $important rule has the absolute priority

Actually, `$badfilter` has absolute priority, in the sense that `$important` rules can be disabled by it, just like any other rule.
Examples:
* `||somesite.com^$important` can be disabled by` ||somesite.com^$important,badfilter`
* `@@||somesite.com^$important` can be disabled by `@@||somesite.com^$important,badfilter`

**Comment by Yuki2718** [comment]
I commented:
> As to $badfilter & $important the former prevents any rule specified to be parsed and loaded on memory, OTOH the latter simply ignores any whitelist (@@) so it's "block anyway!". As you see in my anti-whitelist (BTW, due to the recent white-/black- arguments I'm thinking to change the name) I used only $badfilter for any rule from AdGuard Base because it's not enabled by default on uBO. So these rules do nothing for those who haven't subscribed Base. For the rest of rules it's case-by-case - note $badfilter looses its effectiveness if the original whitelist is changed even slightly i.e. it must be exactly same form except for badfilter appended, only exception is domain= scope which can be different.
