### ISSUE TITLE
Bug: $badrule?

### ISSUE THREAD

**Issue by Yuki2718** [My-External-Stuff/ublockorigin-rules#5]
Hi, actually it's an issue for ublockorigin-rules but as issue tracker is not available for the repo I'm forced to create an issue somewhere else (too early to make PR).

So what is the `badrule`? IF anti_whitelist is for uBlock Origin there's no such modifier supported, what's supported is `badfilter`.

Of note, I also share my tiny anti-whitelist although it's under CC BY-SA 4.0 - I don't know McRae license.

**Comment by spirillen** [comment]
According to the badfilter/important tags, then I found a case that can appear to be related

![image](https://user-images.githubusercontent.com/44526987/147665190-387fdd4d-253d-47b7-bb0f-67bd7334a315.png)

As you can see, then the latest scorecard isn't blocked

![image](https://user-images.githubusercontent.com/44526987/147665287-b528f961-32a6-42dd-8e85-089cb3106ef3.png)

**Comment by Yuki2718** [comment]
What? In the screenshot `https://sb.scorecardresearch.com/beacon.js` is correctly blocked and redirected to neutered resource.

**Comment by spirillen** [comment]
> What? In the screenshot `https://sb.scorecardresearch.com/beacon.js` is correctly blocked and redirected to neutered resource.

Ok, it just a it looks like nothing is done to the rule, color isn't indicating it it stopped.

Thanks Yuki2718
